### ISSUE TITLE
Более тесная интеграция с VKUI

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/vkui-connect-promise#4]
Тикет по теме https://github.com/VKCOM/VKUI/issues/383

**Comment by danakt** [comment]
@mahnunchik привет! Данный пакет будет задепрекейчекн, а функционал перемещён в vk-connect 🙂

**Comment by mahnunchik** [comment]
@danakt это конечно круто! Но когда? Психически здоровому человеку connect без промисов  использовать сложно.

**Comment by danakt** [comment]
@mahnunchik ты можешь использовать коннект с промисами уже сейчас, установив бетку коннекта:
```
yarn add @vkontakte/vk-connect@1.5.6-beta.13-promise
```
Там сейчас есть метод `sendPromise`, однако поскольку это бетка, интерфейс может измениться к релизу. Но, к сожалению, там пока не поддерживаются старые версии приложения ВК на андроиде (с другой стороны здесь тоже), но в ближайшем будущем они будут включены

**Comment by mahnunchik** [comment]
@danakt версия `1.5.6-beta.13-promise` в npm содержит код идентичный стабильной версии `1.5.6` без добавления работы с промисами и метода `sendPromise `.

**Comment by danakt** [comment]
@mahnunchik мне кажется у тебя какие-то проблемы с установкой. Сейчас лично на всякий случай проверил — всё ок
